client_config_backend: settings
client_config:
  client_id: 618222699798-qo05kvoouvnfd7stnuna5qgnjboh6k19.apps.googleusercontent.com
  client_secret: YigIOT21IuemX5s6npegcksI
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://accounts.google.com/o/oauth2/token
  redirect_uri: http://localhost:8080/

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True


